
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    usertag VARCHAR(60) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    ban BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE profiles(
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    main_character VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    level INT NOT NULL,
    rank VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE social(
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    youtube VARCHAR(255) DEFAULT NULL,
    twitch VARCHAR(255) DEFAULT NULL,
    kick VARCHAR(255) DEFAULT NULL,
    discord VARCHAR(255) DEFAULT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE comments(
    id SERIAL PRIMARY KEY,
    profile_id INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    comment VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);